import type {Skill} from './stops';
export type Question={id:string;stopId?:string;skill:Skill;prompt:string;formula?:string;options?:string[];answer:string;hint:string;explanation:string;solution:string;type:'choice'|'numeric';review?:boolean};
export const questions:Question[]=[
{id:'average',skill:'Derivadas',type:'numeric',prompt:"O terreno segue $f(x) = x^{2}$. Qual é a taxa média de variação entre $x = 1$ e $x = 3$?",formula:'m=\\frac{f(3)-f(1)}{3-1}',answer:'4',hint:"Compare a mudança de altura com a mudança horizontal. Calcule $f(3)$ e $f(1)$ separadamente.",explanation:"A diferença entre alturas não é a taxa: ainda precisamos dividi-la pela largura do intervalo.",solution:"$f(3) = 9$ e $f(1) = 1$. Logo, $\\frac{9-1}{3-1} = \\frac{8}{2} = 4$."},
{id:'secant',skill:'Derivadas',type:'choice',prompt:"Elena desenha uma reta passando por dois pontos distintos do gráfico. O que a inclinação dessa reta representa?",options:["A altura do ponto mais alto", "A taxa média de variação no intervalo", "A área entre a curva e o eixo", "Sempre a derivada no primeiro ponto"],answer:'1',hint:"A reta usa informações de dois pontos, e não apenas de um instante.",explanation:"Uma secante mede uma razão entre duas variações ao longo de um intervalo.",solution:"É a taxa média de variação: a variação de $f$ dividida pela variação de $x$."},
{id:'near',skill:'Derivadas',type:'numeric',prompt:"Para $f(x) = x^{2}$, A está em $x = 1$ e $B$ em $x = 1{,}1$. Qual é a inclinação da secante?",formula:'m=2+h,\\quad h=0{,}1',answer:'2.1',hint:"Use a expressão simplificada: some a distância $h$ à inclinação $2$.",explanation:"A inclinação ainda é uma taxa média, pois os dois pontos continuam distintos.",solution:"$m = 2 + 0{,}1 = 2{,}1$. Esse valor já está próximo de $2$."},
{id:'limit',skill:'Derivadas',type:'choice',prompt:"Ao aproximar $B$ de $A$ pelos dois lados, as inclinações tendem a $2$. O que isso nos diz?",options:["Que a altura de $A$ é $2$", "Que a função é constante", "Que $f'(1) = 2$, a inclinação da tangente", "Que podemos dividir diretamente por zero"],answer:'2',hint:"O limite das taxas médias descreve a mudança local da função.",explanation:"Não substituímos $h = 0$ no quociente. Observamos o valor ao qual ele tende.",solution:"A derivada $f'(1) = 2$ é a inclinação da reta tangente em $A = (1,1)$."},
{id:'error',skill:'Derivadas',type:'choice',prompt:"Um viajante substituiu $h = 0$ no quociente da derivada e concluiu: “$\\frac{0}{0} = 0$, então a derivada é zero”. Onde está o erro?",options:["$\\frac{0}{0}$ é uma indeterminação; precisamos calcular o limite", "Toda derivada vale $1$", "Uma tangente precisa passar pela origem", "O valor de $h$ nunca pode se aproximar de zero"],answer:'0',hint:"Um quociente com denominador zero não fornece um número real.",explanation:"O limite pode existir mesmo quando a expressão original não está definida no ponto.",solution:"$\\frac{0}{0}$ não é zero. Para $h \\ne 0$, simplificamos o quociente para $2 + h$ e então calculamos seu limite: $2$."}
];
export const trainingQuestions:Question[]=[
{id:'train-average',skill:'Derivadas',type:'numeric',prompt:"Revisão: qual é a taxa média de $f(x) = x^{2}$ entre $x = 2$ e $x = 4$?",answer:'6',hint:"Use a diferença das imagens dividida pela diferença dos valores de $x$.",explanation:"As imagens são $4$ e $16$; a largura do intervalo é $2$.",solution:"$\\frac{16-4}{4-2} = \\frac{12}{2} = 6$.",review:true},
{id:'train-tangent',skill:'Derivadas',type:'numeric',prompt:"Para $f(x) = x^{2}$, as secantes em torno de $x = 2$ têm inclinação $4 + h$. Quanto vale $f'(2)$?",answer:'4',hint:"Observe a expressão quando $h$ tende a zero.",explanation:"O termo $h$ desaparece no limite, mas o termo constante permanece.",solution:"$\\lim (4 + h) = 4$ quando $h \\to 0$. Portanto, $f'(2) = 4$.",review:true},
{...questions[4],id:'train-error',review:true}
];
