'use client';
import RichText from './RichText';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Lightbulb,Star,Award,Compass} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import type {Question} from '@/content/questions';
import {lessons} from '@/content/catalog';
import {stops,regions} from '@/content/stops';
import Character from './Character';
import {isCorrect,type AnswerRecord} from '@/lib/game/evaluation';
import type {Run,Mode} from '@/lib/game/progress';
import MathText from './Math';
export default function Duel({mode,onBack,onFinish,challenge,stopId}:{mode:Mode;onBack:()=>void;onFinish:(records:AnswerRecord[],mode:Mode,stopId:string|null)=>Run;challenge:Question[];stopId:string|null}){const [bank]=useState<Question[]>(challenge);const stop=stops.find(s=>s.id===stopId);const guide=lessons[stopId??bank[0]?.stopId??'stop-0'];const [index,setIndex]=useState(0);const [value,setValue]=useState('');const [attempts,setAttempts]=useState(0);const [status,setStatus]=useState<'answer'|'hint'|'detail'|'solution'|'correct'>('answer');const [records,setRecords]=useState<AnswerRecord[]>([]);const [result,setResult]=useState<Run|null>(null);const q=bank[index];function submit(){if(!value.trim()||status==='correct'||status==='solution'||status==='detail')return;const n=attempts+1;setAttempts(n);const correct=isCorrect(q,value);if(correct||n===2){setRecords([...records,{questionId:q.id,stopId:q.stopId,skill:q.skill,correct,firstCorrect:correct&&n===1,attempts:n}]);setStatus(correct?'correct':'detail')}else{setStatus('hint');setValue('')}}function next(){if(index===bank.length-1){setResult(onFinish(records,mode,stopId));return}setIndex(index+1);setValue('');setAttempts(0);setStatus('answer')}if(result)return <main className="result-page"><Award size={52}/><p className="eyebrow">{mode==='preview'?'PRÉVIA FINALIZADA':mode==='training'?'TREINO CONCLUÍDO':result.passed?'PARADA CONQUISTADA':'HÁ MAIS UM CAMINHO A EXPLORAR'}</p><h1>{result.passed?'Uma nova perspectiva.':'A compreensão vem com a prática.'}</h1><div className="result-stars">{[1,2,3].map(n=><Star key={n} size={40} fill={n<=result.stars?'currentColor':'none'}/>)}</div><p className="result-score">{result.score}% <span>de acertos</span></p><p>{mode==='preview'?'Esta simulação não alterou estrelas, progresso ou histórico.':mode==='duel'?(result.passed?(stopId==='stop-21'?'Você concluiu a Estação Final! As três trilhas estão à sua disposição para revisar e aprofundar.':`Você concluiu ${stop?.name}. O caminho até ${stops[stops.findIndex(s=>s.id===stopId)+1]?.name} está aberto.`):'Para conquistar esta parada, alcance pelo menos 70% de acertos. Revise as explicações e tente novamente, no seu ritmo.'):'Seu treino foi registrado e os indicadores das habilidades praticadas foram atualizados.'}</p><div className="result-summary"><span>{records.filter(r=>r.firstCorrect).length} acertos sem dica</span><span>{records.filter(r=>r.correct&&!r.firstCorrect).length} acertos com dica</span></div><button className="primary" onClick={onBack}><Compass size={18}/>{mode==='preview'?'Voltar ao professor':'Retornar ao mapa'}</button><p className="fine">Estrelas: 1 por concluir · 2 por bom desempenho · 3 por acertar tudo sem dicas.</p></main>;
return <main className="duel-page"><div className="lesson-top"><button className="text-btn" onClick={onBack}><ArrowLeft size={17}/>Sair do desafio</button><span className="eyebrow">{mode==='training'?'REVISÃO NO ACAMPAMENTO':mode==='preview'?'PRÉVIA DO PROFESSOR':stop?.name.toUpperCase()}</span></div>{mode==='preview'&&<div className="notice">Teste de conteúdo: suas respostas nesta prévia não alteram o progresso.</div>}<header className="duel-heading"><p className="eyebrow">CONHECIMENTO É A SUA MELHOR FERRAMENTA</p><h1>{mode==='training'?'Hora de relembrar.':'Duelo de ideias'}</h1><p>Sem cronômetro. Pense, experimente e encontre o seu caminho.</p></header><div className="duel-arena"><aside><Character lesson={guide}/><blockquote>“<RichText>{guide.intro}</RichText>”</blockquote></aside><section className="question-paper"><div className="between"><span className="eyebrow">{q.review?'REVISÃO ESPAÇADA':'DESAFIO'} {index+1} DE {bank.length}</span><span className="fine">{mode==='duel'?'Meta: 4 de 5 acertos':'Treine no seu ritmo'}</span></div><Progress value={index/bank.length*100} aria-label="Progresso do duelo"/>{q.review&&<p className="review-source">Revisão de {stops.find(s=>s.id===q.stopId)?.name}</p>}<h2><RichText>{q.prompt}</RichText></h2>{q.formula&&<MathText tex={q.formula} block/>}<form onSubmit={e=>{e.preventDefault();submit()}}>{q.type==='choice'?<RadioGroup aria-label="Sua resposta" value={value} onValueChange={setValue} disabled={['detail','correct','solution'].includes(status)} className="answers">{q.options!.map((o,i)=><label key={o} className={`answer-option ${value===String(i)?'selected':''}`}><RadioGroupItem value={String(i)}/><span><RichText>{o}</RichText></span></label>)}</RadioGroup>:<div className="numeric-answer"><label htmlFor="answer">Sua resposta</label><input id="answer" inputMode="decimal" autoComplete="off" placeholder="Digite um número" value={value} disabled={['detail','correct','solution'].includes(status)} onChange={e=>setValue(e.target.value)}/><small>Aceita vírgula ou ponto decimal.</small></div>}
<div aria-live="polite">{status==='hint'&&<div className="feedback hint"><Lightbulb size={20}/><div><h4>Uma pista para tentar de novo</h4><p><RichText>{q.hint}</RichText></p></div></div>}{status==='detail'&&<div className="feedback hint"><BookIcon/><div><h4>Vamos olhar com mais cuidado</h4><p><RichText>{q.explanation}</RichText></p><button type="button" className="text-btn" onClick={()=>setStatus('solution')}>Ver resolução<ArrowRight size={16}/></button></div></div>}{(status==='correct'||status==='solution')&&<div className={`feedback ${status==='correct'?'success':'hint'}`}><Check size={22}/><div><h4>{status==='correct'?'Caminho certo!':'Entenda a resolução'}</h4><p><RichText>{q.solution}</RichText></p></div></div>}</div>
<div className="question-footer"><span className="fine">{attempts===0?'Até duas tentativas por questão':`${attempts} de 2 tentativas usadas`}</span>{status==='correct'||status==='solution'?<button type="button" className="primary" onClick={next}>{index===bank.length-1?'Ver resultado':'Próxima questão'}<ArrowRight size={17}/></button>:status!=='detail'&&<button type="submit" className="primary" disabled={!value.trim()}>{status==='hint'?'Tentar novamente':'Confirmar resposta'}<ArrowRight size={17}/></button>}</div></form></section></div><p className="fine center">Acertos com dica contam para concluir. O domínio dá mais peso aos acertos sem ajuda.</p></main>}
function BookIcon(){return <Lightbulb size={22}/>}
