'use client';
import {useState,useEffect} from 'react';
import MathText from './Math';
import {Slider} from '@/components/ui/slider';
import {Play,RotateCcw} from 'lucide-react';
const fmt=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
export default function Graph(){const [h,setH]=useState(1.5);const [playing,setPlaying]=useState(false);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setH(v=>{if(Math.abs(v)<.035){setPlaying(false);return 0}return Math.round(v*.86*100)/100}),80);return()=>clearInterval(id)},[playing]);const X=(x:number)=>52+x*130;const Y=(y:number)=>332-y*32;const slope=2+h;const curve=Array.from({length:91},(_,i)=>{const x=i/30;return `${i?'L':'M'}${X(x)},${Y(x*x)}`}).join(' ');return <div className="graph-panel"><div className="graph-title"><span>CADERNO DE CAMPO</span><strong><MathText tex="f(x)=x^2"/></strong></div><svg viewBox="0 0 510 380" role="img" aria-label={`Gráfico de f(x) = x². h = ${fmt(h)}. Inclinação ${fmt(slope)}.`}>
<defs><clipPath id="plotclip"><rect x="45" y="15" width="407" height="333"/></clipPath></defs>
{[0,1,2,3].map(x=><g key={'x'+x}><line x1={X(x)} y1="22" x2={X(x)} y2="332" stroke="#d9cfb8" strokeDasharray="3 5"/><text x={X(x)} y="356" textAnchor="middle">{x}</text></g>)}{[0,2,4,6,8].map(y=><g key={'y'+y}><line x1="52" y1={Y(y)} x2="460" y2={Y(y)} stroke="#d9cfb8" strokeDasharray="3 5"/><text x="33" y={Y(y)+4} textAnchor="end">{y}</text></g>)}
<path d="M52 18V332H472" fill="none" stroke="#665d48" strokeWidth="1.5"/><text x="480" y="338">x</text><text x="26" y="21">y</text>
<g clipPath="url(#plotclip)"><path d={curve} fill="none" stroke="#3c5547" strokeWidth="3.5"/><line x1={X(0)} y1={Y(-1)} x2={X(3)} y2={Y(5)} stroke="#859075" strokeWidth="2" strokeDasharray="6 5"/><line x1={X(0)} y1={Y(1-slope)} x2={X(3)} y2={Y(1+2*slope)} stroke="#b06930" strokeWidth="2.5"/><path d={`M${X(1)} ${Y(1)} H${X(1+h)} V${Y((1+h)**2)}`} fill="none" stroke="#b06930" strokeDasharray="4 4"/><circle cx={X(1)} cy={Y(1)} r="6" fill="#3c5547" stroke="#fff8e9" strokeWidth="2"/>{h!==0&&<circle cx={X(1+h)} cy={Y((1+h)**2)} r="6" fill="#b06930" stroke="#fff8e9" strokeWidth="2"/>}</g><text x={X(1)-20} y={Y(1)-13} className="point-label">A</text>{h!==0&&<text x={X(1+h)+12} y={Y((1+h)**2)-10} className="point-label">B</text>}<text x="390" y="36" fill="#3c5547">f(x) = x²</text></svg>
<div className="graph-key"><span><i className="key-line green"/>Função</span><span><i className="key-line orange"/>{h===0?'Tangente':'Secante'}</span><span><i className="key-line dashed"/>Tangente limite</span></div>
<div className="slider-box"><div className="between"><label id="hlabel">Distância horizontal <MathText tex="h"/></label><strong>{fmt(h)}</strong></div><Slider ref={node=>{node?.querySelector('[role="slider"]')?.setAttribute('aria-labelledby','hlabel')}} aria-labelledby="hlabel" min={-.9} max={1.8} step={.01} value={[h]} onValueChange={v=>{setPlaying(false);setH(v[0])}}/><div className="range-labels"><span>−0,9 · pela esquerda</span><span>1,8 · pela direita</span></div><div className="graph-stats"><div><small>{h===0?'Inclinação da tangente':'Inclinação da secante'}</small><strong>{fmt(slope)}</strong></div><button className="text-btn" onClick={()=>{if(h===0)setH(1.5);setPlaying(v=>!v)}}><Play size={14}/>{playing?'Pausar':'Aproximar pontos'}</button><button className="icon-btn" aria-label="Reiniciar gráfico" onClick={()=>{setPlaying(false);setH(1.5)}}><RotateCcw size={16}/></button></div><p className="fine">{h===0?'A e B coincidem. A tangente é definida pelo limite, não por uma divisão por zero.':'Arraste o controle, use as setas do teclado ou anime a aproximação.'}</p></div></div>}
