import {stops,skills,stopStatus,type Skill} from '@/content/stops';
import {allQuestions,lessons} from '@/content/catalog';
import {evaluate,type AnswerRecord} from './evaluation';
export type Mode='duel'|'training'|'preview';
export type Run={id:string;date:string;mode:Mode;stopId:string|null;records:AnswerRecord[];score:number;passed:boolean;stars:number;mastery:number};
export type ProgressData={version:2;completed:string[];stars:number;starsByStop:Record<string,number>;history:Run[];lessonSteps:Record<string,number>};
export const initial:ProgressData={version:2,completed:[],stars:0,starsByStop:{},history:[],lessonSteps:{}};
const known=new Set(stops.map(s=>s.id));
const questionLookup=new Map(allQuestions.map(q=>[q.id,q]));
export function migrate(raw:unknown):ProgressData{if(!raw||typeof raw!=='object')throw Error('Dados de progresso inválidos.');const d=raw as Record<string,any>;if(![1,2].includes(d.version)||!Array.isArray(d.completed)||!Array.isArray(d.history))throw Error('Formato de progresso não reconhecido.');const completed=d.completed.filter((s:unknown)=>typeof s==='string'&&known.has(s));const starsByStop:Record<string,number>={};const source=d.version===1?{mirante:d.stars}:d.starsByStop??{};for(const [id,n]of Object.entries(source))if(completed.includes(id)&&typeof n==='number'&&Number.isFinite(n))starsByStop[id]=Math.max(0,Math.min(3,Math.floor(n)));const history:Run[]=d.history.filter((r:any)=>r&&Array.isArray(r.records)&&typeof r.date==='string'&&Number.isFinite(Date.parse(r.date))).map((r:any,i:number)=>({...r,id:typeof r.id==='string'?r.id:`legacy-${i}`,stopId:known.has(r.stopId)?r.stopId:d.version===1?'mirante':null,mode:r.mode==='training'?'training':'duel',records:r.records.filter((a:any)=>a&&questionLookup.has(a.questionId)).map((a:any)=>({...a,skill:questionLookup.get(a.questionId)!.skill,stopId:questionLookup.get(a.questionId)!.stopId,attempts:a.attempts===2?2:1,correct:!!a.correct,firstCorrect:!!a.firstCorrect&&!!a.correct}))}));const lessonSteps:Record<string,number>={};const sourceSteps=d.version===1?{mirante:d.lessonStep}:d.lessonSteps??{};for(const [id,n]of Object.entries(sourceSteps))if(known.has(id)&&typeof n==='number'&&Number.isFinite(n))lessonSteps[id]=Math.max(0,Math.min(Math.floor(n),lessons[id].steps.length+lessons[id].example.length-1));return {version:2,completed,starsByStop,stars:Object.values(starsByStop).reduce((s,n)=>s+n,0),history,lessonSteps}}
export function applyRun(data:ProgressData,run:Run):ProgressData{if(run.mode==='preview')return data;const completed=[...data.completed];const starsByStop={...data.starsByStop};if(run.mode==='duel'&&run.stopId&&known.has(run.stopId)&&run.passed){const stop=stops.find(s=>s.id===run.stopId)!;if(stopStatus(stop,data.completed)==='locked')throw Error('Conclua os pré-requisitos antes desta parada.');if(!completed.includes(run.stopId))completed.push(run.stopId);starsByStop[run.stopId]=Math.max(starsByStop[run.stopId]??0,run.stars)}return {...data,completed,starsByStop,stars:Object.values(starsByStop).reduce((s,n)=>s+n,0),history:[...data.history,run]}}
export function createRun(records:AnswerRecord[],mode:Mode,stopId:string|null):Run{if(records.length<3||records.length>5)throw Error('O desafio deve ter de 3 a 5 respostas.');return {...evaluate(records),id:typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`,date:new Date().toISOString(),mode,stopId,records}}
export function masteryBySkill(data:ProgressData):Record<Skill,{score:number|null;covered:number;total:number}>{return Object.fromEntries(skills.map(skill=>{const relevant=stops.filter(s=>lessons[s.id].skill===skill);const marks=relevant.map(s=>{const rows=data.history.flatMap(run=>run.records).filter(a=>(a.stopId??questionLookup.get(a.questionId)?.stopId)===s.id).slice(-15);return rows.length?Math.round(rows.reduce((sum,a)=>sum+(a.firstCorrect?100:a.correct?65:0),0)/rows.length):null});const covered=marks.filter((n):n is number=>n!==null);return [skill,{score:covered.length?Math.round(covered.reduce((s,n)=>s+n,0)/covered.length):null,covered:covered.length,total:relevant.length}]})) as Record<Skill,{score:number|null;covered:number;total:number}>}
export function reviewStatus(data:ProgressData,qid:string,now=Date.now()){const sightings=data.history.flatMap(run=>run.records.filter(a=>a.questionId===qid).map(record=>({record,date:run.date})));const last=sightings.at(-1);if(!last)return {due:true,dueAt:0,priority:1};const success=sightings.slice(-3).every(a=>a.record.firstCorrect);const days=!last.record.correct?0:!last.record.firstCorrect?1:success&&sightings.length>=3?14:sightings.length>=2?7:3;const dueAt=Date.parse(last.date)+days*86400000;return {due:dueAt<=now,dueAt,priority:last.record.correct?last.record.firstCorrect?3:1:0}}
export function buildChallenge(data:ProgressData,stopId:string|null,mode:Mode):import('@/content/questions').Question[]{if(mode==='preview')return [...lessons[stopId!].questions];const studied=new Set(data.history.flatMap(run=>run.records.map(a=>a.stopId??questionLookup.get(a.questionId)?.stopId)));const eligible=allQuestions.filter(q=>studied.has(q.stopId)&&q.stopId!==stopId);eligible.sort((a,b)=>{const x=reviewStatus(data,a.id),y=reviewStatus(data,b.id);return Number(y.due)-Number(x.due)||x.priority-y.priority||x.dueAt-y.dueAt||a.id.localeCompare(b.id)});if(mode==='training'){const pool=allQuestions.filter(q=>studied.has(q.stopId));pool.sort((a,b)=>{const x=reviewStatus(data,a.id),y=reviewStatus(data,b.id);return Number(y.due)-Number(x.due)||x.priority-y.priority||x.dueAt-y.dueAt||a.id.localeCompare(b.id)});return pool.slice(0,5).map(q=>({...q,review:true}))}const own=lessons[stopId!].questions;const offset=data.history.filter(r=>r.stopId===stopId&&r.mode==='duel').length%own.length;const rotated=[...own.slice(offset),...own.slice(0,offset)];const review=eligible.find(q=>reviewStatus(data,q.id).due);return review?[...rotated.slice(0,4),{...review,review:true}]:rotated.slice(0,5)}
